spin_manifest = "spin.toml"
dockerfile = ""
kubernetes_resources = ""

[cluster]
  subscription = "26ad903f-2330-429d-8389-864ac35c4350"
  resource_group = "davidgamerotest"
  name = "davidgamerotest"

[container_registry]
  subscription = "26ad903f-2330-429d-8389-864ac35c4350"
  resource_group = "davidgamerotest"
  name = "davidgamerotest"

[keyvault]
  subscription = "26ad903f-2330-429d-8389-864ac35c4350"
  resource_group = "davidgamerotest"
  name = "davidgamerotestq"
